package tests;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import fxPht.DynamicList;


/**
 * @author varajala
 * @version Feb 18, 2021
 */
public class DynamicListTest {
    
    private final int TEST_LIMIT = 100000;
   
    /**
     * Testing the empty contructor with different types.
     */
    @Test 
    public void testEmptyConstructor() {
        DynamicList<Integer> intList = new DynamicList<Integer>();
        assertEquals(intList.count(), 0);
    
        DynamicList<String> strList = new DynamicList<String>();
        assertEquals(strList.count(), 0);
   }

    /**
     * Testing the contructor with provided array.
     */
    @Test 
    public void testArrayConstructor() {
        String[] array1 = {"1", "2", "3", "4", "5"}; 
        DynamicList<String> list1 = new DynamicList<String>(array1);
        assertEquals(list1.count(), array1.length);
    
        String[] array2 = {
            "1", "2", "3", "4", "5",
            "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15",
            "16", "17", "18", "19", "20",
            }; 
        DynamicList<String> list2 = new DynamicList<String>(array2);
        assertEquals(list2.count(), array2.length);
   }
    
    
    /**
     * Test toString-method.
     */
    @Test
    public void testToString() {
        String[] array1 = {"1", "2", "3", "4", "5"}; 
        DynamicList<String> list1 = new DynamicList<String>(array1);
        assertEquals(list1.toString(), Arrays.toString(array1));
    
        String[] array2 = {
            "1", "2", "3", "4", "5",
            "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15",
            "16", "17", "18", "19", "20",
            }; 
        DynamicList<String> list2 = new DynamicList<String>(array2);
        assertEquals(list2.toString(), Arrays.toString(array2));
    }
    
    
    /**
     * Test indexing with valid indexes.
     */
    @Test
    public void testValidIndexing() {
        String[] array1 = {"0", "1", "2", "3", "4"}; 
        DynamicList<String> list1 = new DynamicList<String>(array1);
        assertEquals(list1.get(0), "0");
        assertEquals(list1.get(1), "1");
        assertEquals(list1.get(2), "2");
        assertEquals(list1.get(3), "3");
        assertEquals(list1.get(4), "4");
        
        assertEquals(list1.get(-1), "4");
        assertEquals(list1.get(-2), "3");
        assertEquals(list1.get(-3), "2");
        assertEquals(list1.get(-4), "1");
        assertEquals(list1.get(-5), "0");
    }
    
    
    /**
     * Test indexing with indexes known to fail.
     */
    @Test
    public void testInvalidIndexing() {
        String[] array1 = {"0", "1", "2", "3", "4"}; 
        DynamicList<String> list1 = new DynamicList<String>(array1);
        int[] indexes = {-10, 6, 5, -11};
        for (int i : indexes) {
            try {
                list1.get(i);
                System.out.printf("Indexing succeeded with index: %d%n", i);
                fail();
            } catch (Exception e) {
                assertTrue(true);
            }
        }
    }
    
    
    /**
     * Test appending and expansion.
     */
    @Test
    public void testAppending() {
        DynamicList<Integer> list = new DynamicList<Integer>();
        for (int i = 0; i < TEST_LIMIT; i++) {
            list.append(Integer.valueOf(i));
        }
        assertEquals(list.count(), TEST_LIMIT);
        testPopping(list);
    }
    
    
    /**
     * Test popping items and shrinking the list.
     * @param list List generated by testAppending - method.
     */
    public void testPopping(DynamicList<Integer> list) {
        for (int i = TEST_LIMIT-1; i >= 0; i--) {
            list.pop(i);
        }
        assertEquals(list.count(), 0);
    }
}
